---
- name: Install Apache2 and MySQL
  hosts: db01
  become: yes  # Run tasks with root privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
