---
- name: Webserver setup
  hosts: ec2_dev
  become: yes
  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: present

    - name: Run Apache2 status script
      shell: systemctl status apache2
      register: apache_status_output

    - name: Display Apache2 status
      debug:
        var: apache_status_output.stdout_lines

- name: Database server
  hosts: ec2_dev
  become: yes
  tasks:
    - name: Mariadb server
      apt:
        name: mariadb-server
        state: present
