---
- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install apache
      ansible.builtin.apt:
        name: apache2
        state: present    
    
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: yes

- name: Database server
  hosts: webservers
  become: yes
  tasks:
    - name: Mariadb server
      ansible.builtin.apt:
        name: mariadb-server
        state: present