---
- name: Webserver setup
  hosts: db01
  become: yes
  tasks:
    - name: Remove apache
      ansible.builtin.apt:
        name: apache2
        state: absent

- name: Remove mysql
  hosts: db01
  become: yes
  tasks:
    - name: Remove mysql Server
      ansible.builtin.apt:
        name: mysql
        state: absent